Translate descriptions
CheckIO-to-German/The-Greatest-Common-Divisor pull request #2
Opened 2017-06-03 21:06 UTC by DahliaSR

Closes #1

2017-06-04 20:27 UTC, GiForce approved these changes
🌟

2017-06-04 20:52 UTC, GiForce commented on translations/de/task_short_description.html
> +Teilen, großartig bei Zahlen, Essen, Arbeit und vergrabenen Schätzen. Nicht so sehr in der
Mich stört: _großartig bei Zahlen, ..._ aber: [großartig] _nicht so sehr in der Politik_.
"Für" würde besser klingen, geht für beides. Für die Politik ist das Teilen nicht grossartig. Für Zahlen schon, auch für vergrabene Schätze. Obwohl mit den Zahlen habe ich gerade etwas Mühe, es ist ja für den Anwender großartig. Mal sehen, Teilen ist großartig für Zahlen, um Sie in kleinere und handlichere Teile zu verwandeln. Zahlen waren noch nie so lieb wie nach dem Teilen ^^ Für sich allein wäre "mit" hier am besten. Für was soll Teilen gut sein? Für Zahlen, Essen, Arbeit. Für die Arbeit großartig, schneller und effizienter erledigt. Und hätten Schätze Gefühle, fänden Sie es auch grossartig mehr unter die Leute zu kommen ^^ Mhh, vielleicht geht ja "mit" als Universallösung? Ich überlasse Dir die Entscheidung.

2017-06-04 20:54 UTC, GiForce requested changes
.

2017-06-06 17:14 UTC, DahliaSR commented on translations/de/task_short_description.html
> +Teilen, großartig bei Zahlen, Essen, Arbeit und vergrabenen Schätzen. Nicht so sehr in der
Da weder Zahlen, Essen, Arbeit noch Schätze etwas davon haben geteilt zu werden funktioniert **_für_** hier nicht wirklich.

**_Mit_** geht auch nicht nicht wirklich... Denn das Problem liegt ja nicht bei der Politik, sondern bei den Politikern.

Wie wärs hiermit:  
_Teilen ist großartig bei Zahlen, Essen, Arbeit und vergrabenen Schätzen. In der Politik ist es aber unbeliebt._

2017-06-06 18:07 UTC, GiForce commented
Naja, ich dachte mit "für" meint man in diesem Fall eben nicht das diese Dinge an sich etwas davon haben, sondern die Auseinandersetzung mit diesen Dingen, zum Beispiel kann man ja auch sagen "Jene Jacke ist großartig für lange Regenspaziergänge".
Ob das Problem bei der Politik oder den Politikern liegt, ist das nicht beinahe eine philosophische Frage?
Aber Dein Vorschlag birgt eine großartige Lösung; "beliebt" anstelle großartig schon im ersten Teil, etwa so
Teilen ist beliebt bei Zahlen, Essen, Arbeit und vergrabenen Schätzen. In der Politik eher weniger. 
Ich glaube so ist das jetzt schön elegant gesagt.
🥂

> On 6 Jun 2017, at 19:14, DahliaSR <notifications@github.com> wrote:
> 
> @DahliaSR commented on this pull request.
> 
> In translations/de/task_short_description.html:
> 
> > \ No newline at end of file
> +Teilen, großartig bei Zahlen, Essen, Arbeit und vergrabenen Schätzen. Nicht so sehr in der
> Da weder Zahlen, Essen, Arbeit noch Schätze etwas davon haben geteilt zu werden funktioniert für hier nicht wirklich.
> 
> Mit geht auch nicht nicht wirklich... Denn das Problem liegt ja nicht bei der Politik, sondern bei den Politikern.
> 
> Wie wärs hiermit:
> Teilen ist großartig bei Zahlen, Essen, Arbeit und vergrabenen Schätzen. In der Politik ist es aber unbeliebt.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-06-09 17:23 UTC, DahliaSR commented
@GiForce 
Approval, pls!

2017-06-09 19:13 UTC, GiForce approved these changes
💫

2017-06-09 20:36 UTC, merged